### ISSUE TITLE
[EPIC] Add the project to Operate First Website 

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/github-labeler#89]
- [x] Re-do the Readme file to match the format for all Data science projects on Opf
- [x] Add the project to Operate-first Data Science Page
- [x] (https://github.com/operate-first/operate-first.github.io/issues/319)

**Comment by antter** [comment]
Closing bc the project is now on the website

**Comment by aakankshaduggal** [comment]
@antter 
![image](https://user-images.githubusercontent.com/26301643/140940873-621c50cf-56ff-46f4-b8e6-894c8743a29c.png)
The project has to show up here on the sidebar with all the related content.

You could look my PR that adds Operate First Data Science Meetup to the page - https://github.com/operate-first/operate-first.github.io/pull/323

**Comment by antter** [comment]
Ok just did it https://github.com/operate-first/operate-first.github.io/pull/324
